name: Bug Report
description: Report an issue with AdGuard Filters Registry (incorrect metadata of the filter or other related issues).
labels: ["A: Bug"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        To avoid invalid reports, please check and confirm following checkboxes.
      options:
        - label: This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
          required: true
        - label: You're using an up-to-date version of the problematic filter;
          required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      placeholder: |
          Please add a simple and clear description of the problem.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: |
          Suggest a possible solution in a clear and concise manner.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Privacy
      description: By submitting this issue, you agree that report does not contain private info
      options:
        - label: I agree to follow this condition
          required: true
