blank_issues_enabled: false
contact_links:
  - name: AdGuard Filters Registry documentaion
    url: https://github.com/AdguardTeam/FiltersRegistry/blob/master/README.md
    about: Useful information that is necessary for adding new filters.
