name: Build Third-party filters

on:
  # For manual run builds
  workflow_dispatch:
  # Runs every 4 hours.
  schedule:
    - cron: "0 */4 * * *"

env:
  BUILD_MODE: 3p

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with depth 1
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build filters
        run: yarn auto-build --mode ${{ env.BUILD_MODE }}

      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        if: github.ref == 'refs/heads/master' && github.repository == 'AdguardTeam/FiltersRegistry'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
          message: "skip ci: auto-build ${{ env.BUILD_MODE }} filters"
