name: Build AdGuard filters

on:
  # For manual run builds
  workflow_dispatch:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  pull_request:
    paths-ignore:
      # Do not trigger build on changes to the following files.
      # It is needed to avoid pull request merge blocking
      # as compiler does not use the updated config during the build.
      - "optimization_config.json"

env:
  BUILD_MODE: adguard

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with depth 1
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build filters
        run: yarn auto-build --mode ${{ env.BUILD_MODE }}

      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        if: github.ref == 'refs/heads/master' && github.repository == 'AdguardTeam/FiltersRegistry' && github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
          message: "skip ci: auto-build ${{ env.BUILD_MODE }} filters"
