name: Test build filters and patches

on:
  # For manual run builds
  workflow_dispatch:
  push:
    paths-ignore:
      # do not trigger build on changes to the following files.
      # it is needed to avoid pull request merge blocking
      # as compiler does not use the updated config during the build.
      - 'optimization_config.json'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with depth 1
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      # TODO: add a separate workflow for linting
      - name: Lint
        run: yarn lint

      - name: Build filters
        run: TLS=insecure yarn build

      - name: Build patches
        # Does not matter how long patches are valid because
        # these patches (as well as filter) would not be merged to master,
        # so for example set it to '10 minutes' in seconds.
        run: yarn build:patches --time=600 --resolution=s

      - name: Validate platforms and locales
        run: yarn validate
